# Notebook 1: Benchmark Construction

## Research Project
**Evaluating the Functional Correctness and Consistency of AI-Generated Introductory Programming Solutions: Implications for Computing Education**

**Author:** Dr. C. V. Krishnaveni  
Department of Computer Science  
SKR & SKR Government College for Women (Autonomous), Kadapa

**GitHub Repository:** https://github.com/vkchennuru/AI-Code_Judgement

**Notebook:** 1 of 7

---

## Objective

This notebook loads and validates the CS1 benchmark dataset used throughout the research.

### Input
- dataset/cs1_problems.csv

### Output
- dataset/cs1_problems_clean.csv

### Workflow

1. Clone the GitHub repository
2. Load the benchmark dataset
3. Validate the dataset
4. Check missing values
5. Check duplicate records
6. Save the cleaned dataset

## Requirements

This notebook requires the following Python packages:

- pandas

Google Colab includes these packages by default.

If running locally, install them using:

```bash
pip install pandas
```

In [3]:
# ============================================================
# Clone GitHub Repository
# ============================================================

!rm -rf AI-Code_Judgement

!git clone https://github.com/vkchennuru/AI-Code_Judgement.git

Cloning into 'AI-Code_Judgement'...
remote: Enumerating objects: 165, done.
remote: Counting objects: 100% (165/165), done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 165 (delta 65), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (165/165), 402.91 KiB | 2.65 MiB/s, done.
Resolving deltas: 100% (65/65), done.

In [4]:
from pathlib import Path
import pandas as pd

In [5]:
PROJECT_ROOT = Path("/content/AI-Code_Judgement")

DATASET_PATH = PROJECT_ROOT / "dataset" / "cs1_problems.csv"

OUTPUT_PATH = PROJECT_ROOT / "dataset" / "cs1_problems_clean.csv"

print(DATASET_PATH)

/content/AI-Code_Judgement/dataset/cs1_problems.csv

## Step 1: Load the Benchmark Dataset

The benchmark dataset contains introductory programming problems that will be used throughout the experimental pipeline.

This section loads the dataset and confirms that it has been read successfully.

In [6]:
# ============================================================
# Load Benchmark Dataset
# ============================================================

df = pd.read_csv(DATASET_PATH)

print("✓ Dataset loaded successfully.")
print(f"Number of rows    : {df.shape[0]}")
print(f"Number of columns : {df.shape[1]}")

✓ Dataset loaded successfully.
Number of rows    : 10
Number of columns : 12

In [7]:
# Display first five records

df.head()

,problem_id,title,topic,difficulty,problem_statement,input_format,output_format,constraints,sample_input,sample_output,expected_algorithm,concepts
0,1,Sum of Two Integers,Variables,Easy,Write a Python program that reads two integers...,Two integers separated by a space.,Print a single integer representing their sum.,"-10^9 ? a, b ? 10^9",5 10,15,Addition,"Variables, Input, Output"
1,2,Area of a Circle,Operators,Easy,Write a Python program that reads the radius o...,One positive real number representing the radius.,Print the area rounded to two decimal places.,0 ? radius ? 10^4,5,78.54,Formula (?r²),"Operators, Arithmetic"
2,3,Largest of Two Numbers,Selection,Easy,Write a Python program that reads two integers...,Two integers separated by a space.,Print the larger integer.,"-10^9 ? a, b ? 10^9",12 7,12,Conditional Selection,"If Statement, Comparison"
3,4,Print Numbers from 1 to N,Loops,Easy,Write a Python program that reads an integer N...,One positive integer N.,Numbers from 1 to N separated by spaces.,1 ? N ? 1000,5,1 2 3 4 5,Iteration,Loops
4,5,Factorial of a Number,Loops,Easy,Write a Python program that reads a non-negati...,One non-negative integer.,Print the factorial value.,0 ? N ? 20,5,120,Iterative Multiplication,Loops

## Step 2: Dataset Information

This section displays the dataset structure, column names, and data types.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   problem_id          10 non-null     int64
 1   title               10 non-null     object
 2   topic               10 non-null     object
 3   difficulty          10 non-null     object
 4   problem_statement   10 non-null     object
 5   input_format        10 non-null     object
 6   output_format       10 non-null     object
 7   constraints         10 non-null     object
 8   sample_input        10 non-null     object
 9   sample_output       10 non-null     object
 10  expected_algorithm  10 non-null     object
 11  concepts            10 non-null     object
dtypes: int64(1), object(11)
memory usage: 1.1+ KB

In [9]:
print("Column Names")

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

Column Names
1. problem_id
2. title
3. topic
4. difficulty
5. problem_statement
6. input_format
7. output_format
8. constraints
9. sample_input
10. sample_output
11. expected_algorithm
12. concepts

## Step 3: Missing Value Analysis

Checking whether any records contain missing values.

In [10]:
missing_values = df.isnull().sum()

print("Missing Values")

missing_values

Missing Values

problem_id            0
title                 0
topic                 0
difficulty            0
problem_statement     0
input_format          0
output_format         0
constraints           0
sample_input          0
sample_output         0
expected_algorithm    0
concepts              0
dtype: int64

In [11]:
if missing_values.sum() == 0:
    print("✓ No missing values found.")
else:
    print("⚠ Missing values detected.")

✓ No missing values found.

## Step 4: Duplicate Record Analysis

Checking for duplicate programming problems.

In [12]:
duplicate_rows = df.duplicated().sum()

print(f"Duplicate Rows : {duplicate_rows}")

Duplicate Rows : 0

In [13]:
if duplicate_rows == 0:
    print("✓ No duplicate records found.")
else:
    print("⚠ Duplicate records detected.")

✓ No duplicate records found.

## Step 5: Dataset Summary Statistics

In [14]:
df.describe(include="all")

,problem_id,title,topic,difficulty,problem_statement,input_format,output_format,constraints,sample_input,sample_output,expected_algorithm,concepts
count,10.00000,10,10,10,10,10,10,10,10,10,10,10
unique,NaN,10,9,2,10,9,10,8,8,9,10,9
top,NaN,Sum of Two Integers,Loops,Easy,Write a Python program that reads two integers...,Two integers separated by a space.,Print a single integer representing their sum.,"-10^9 ? a, b ? 10^9",5,15,Addition,Loops
freq,NaN,1,2,5,1,2,1,2,3,2,1,2
mean,5.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,3.02765,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,5.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,7.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,10.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Step 6: Benchmark Quality Validation

This section validates the quality of the benchmark dataset by checking:

- Number of programming problems
- Availability of required columns
- Dataset uniqueness
- Data integrity

These checks ensure that the benchmark dataset is suitable for subsequent experiments.

In [15]:
# ============================================================
# Benchmark Quality Validation
# ============================================================

print("=" * 60)
print("Benchmark Validation")
print("=" * 60)

print(f"Total Programming Problems : {len(df)}")
print(f"Total Features             : {len(df.columns)}")

============================================================
Benchmark Validation
============================================================
Total Programming Problems : 10
Total Features             : 12

In [16]:
print("\nDataset Columns\n")

for col in df.columns:
    print("✓", col)

Dataset Columns

✓ problem_id
✓ title
✓ topic
✓ difficulty
✓ problem_statement
✓ input_format
✓ output_format
✓ constraints
✓ sample_input
✓ sample_output
✓ expected_algorithm
✓ concepts

In [17]:
print("\nData Types\n")

print(df.dtypes)

Data Types

problem_id             int64
title                 object
topic                 object
difficulty            object
problem_statement     object
input_format          object
output_format         object
constraints           object
sample_input          object
sample_output         object
expected_algorithm    object
concepts              object
dtype: object

## Step 7: Dataset Preview

The following sample records provide a quick overview of the benchmark dataset.

In [18]:
display(df.sample(min(5, len(df)), random_state=42))

,problem_id,title,topic,difficulty,problem_statement,input_format,output_format,constraints,sample_input,sample_output,expected_algorithm,concepts
8,9,Word Frequency Counter,Dictionaries,Medium,Write a Python program that reads a sentence a...,One line containing a sentence.,"Print each word followed by its frequency, one...",Up to 100 words,apple banana apple,apple 2?banana 1,Dictionary Counting,Dictionaries
1,2,Area of a Circle,Operators,Easy,Write a Python program that reads the radius o...,One positive real number representing the radius.,Print the area rounded to two decimal places.,0 ? radius ? 10^4,5,78.54,Formula (?r²),"Operators, Arithmetic"
5,6,Prime Number Check,Functions,Medium,Write a Python program that defines a function...,One positive integer.,"Print ""Prime"" or ""Not Prime"".",1 ? N ? 10^6,13,Prime,Trial Division,Functions
0,1,Sum of Two Integers,Variables,Easy,Write a Python program that reads two integers...,Two integers separated by a space.,Print a single integer representing their sum.,"-10^9 ? a, b ? 10^9",5 10,15,Addition,"Variables, Input, Output"
7,8,Count Vowels in a String,Strings,Medium,Write a Python program that reads a string and...,One line containing a string.,Print the total number of vowels.,Length ? 1000 characters,Artificial Intelligence,10,Character Traversal,Strings

## Step 8: Save Clean Benchmark Dataset

The validated benchmark dataset is saved for use in the remaining notebooks.

In [19]:
# ============================================================
# Save Clean Dataset
# ============================================================

df.to_csv(OUTPUT_PATH, index=False)

print("✓ Clean dataset saved successfully.")
print("Output File:")
print(OUTPUT_PATH)

✓ Clean dataset saved successfully.
Output File:
/content/AI-Code_Judgement/dataset/cs1_problems_clean.csv

In [20]:
print("Output Exists:", OUTPUT_PATH.exists())

if OUTPUT_PATH.exists():
    print("✓ Benchmark dataset saved successfully.")
else:
    print("✗ Failed to save benchmark dataset.")

Output Exists: True
✓ Benchmark dataset saved successfully.

## Reproducibility

This notebook is designed to be fully reproducible.

To reproduce the results:

1. Clone the GitHub repository.
2. Open this notebook in Google Colab.
3. Run **Runtime → Run all**.
4. The cleaned benchmark dataset will be generated automatically.

# Conclusion

Notebook 1 successfully completed the following tasks:

- Loaded the CS1 benchmark dataset.
- Validated dataset structure and integrity.
- Checked missing values.
- Checked duplicate records.
- Examined dataset characteristics.
- Saved a cleaned benchmark dataset.

The generated file:

`dataset/cs1_problems_clean.csv`

will serve as the input for **Notebook 2: Prompt Preparation**.

In [21]:
print("=" * 60)
print("Notebook 1 completed successfully.")
print("Output:", OUTPUT_PATH)
print("=" * 60)

============================================================
Notebook 1 completed successfully.
Output: /content/AI-Code_Judgement/dataset/cs1_problems_clean.csv
============================================================