# Notebook 3: AI Code Generation

**Project:** Evaluating the Functional Correctness and Consistency of AI-Generated Introductory Programming Solutions: Implications for Computing Education

**Author:** Dr. C. V. Krishnaveni

**Institution:** Department of Computer Science, SKR & SKR Government College for Women (Autonomous), Kadapa, Andhra Pradesh, India

---

## Objective

This notebook generates AI solutions for each benchmark programming problem using standardized prompts prepared in Notebook 2.

Each benchmark problem is independently submitted to the Large Language Model (LLM) three times to evaluate response consistency and functional correctness.

The generated solutions are stored in a structured directory for subsequent functional evaluation.

## Workflow

This notebook performs the following tasks:

1. Clone the GitHub repository.
2. Load the prompt manifest generated in Notebook 2.
3. Create the directory structure for generated solutions.
4. Generate three independent AI solutions for each benchmark problem.
5. Save each solution as a Python source file.
6. Verify that all generated files have been stored correctly.

## Requirements

Python Version

- Python 3.11 or later

Required Libraries

- pandas
- pathlib
- os

In [20]:
# ============================================================
# Clone GitHub Repository
# ============================================================

!rm -rf AI-Code_Judgement

!git clone https://github.com/vkchennuru/AI-Code_Judgement.git

Cloning into 'AI-Code_Judgement'...
remote: Enumerating objects: 153, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 153 (delta 56), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (153/153), 383.51 KiB | 9.83 MiB/s, done.
Resolving deltas: 100% (56/56), done.

In [21]:
# ============================================================
# Import Libraries
# ============================================================

import os
import pandas as pd
from pathlib import Path

In [22]:
# ============================================================
# Define Project Paths
# ============================================================

PROJECT_ROOT = Path("/content/AI-Code_Judgement")

PROMPTS_DIR = PROJECT_ROOT / "prompts"

GENERATED_CODE_DIR = PROJECT_ROOT / "generated_code"

RESULTS_DIR = PROJECT_ROOT / "results"

GENERATED_CODE_DIR.mkdir(parents=True, exist_ok=True)

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print("Project Root :", PROJECT_ROOT)
print("Prompt Folder:", PROMPTS_DIR)
print("Generated Code Folder:", GENERATED_CODE_DIR)

Project Root : /content/AI-Code_Judgement
Prompt Folder: /content/AI-Code_Judgement/prompts
Generated Code Folder: /content/AI-Code_Judgement/generated_code

## Load Prompt Manifest

The prompt manifest created in Notebook 2 maps benchmark problems to their corresponding prompt files.

In [23]:
manifest_path = PROMPTS_DIR / "prompt_manifest.csv"

manifest_df = pd.read_csv(manifest_path)

display(manifest_df.head())

print()

print(f"Total Prompt Files : {len(manifest_df)}")

,problem_id,title,prompt_file,solution_A,solution_B,solution_C,status
0,1,Sum of Two Integers,problem_001_prompt.txt,NaN,NaN,NaN,Generated
1,2,Area of a Circle,problem_002_prompt.txt,NaN,NaN,NaN,Generated
2,3,Largest of Two Numbers,problem_003_prompt.txt,NaN,NaN,NaN,Generated
3,4,Print Numbers from 1 to N,problem_004_prompt.txt,NaN,NaN,NaN,Generated
4,5,Factorial of a Number,problem_005_prompt.txt,NaN,NaN,NaN,Generated

Total Prompt Files : 10

## Identify Prompt Files

The prompt manifest is used to locate all prompt files that will be submitted to the Large Language Model (LLM) during the code generation stage.

In [24]:
# ============================================================
# Locate Prompt Files
# ============================================================

prompt_files = []

for _, row in manifest_df.iterrows():

    prompt_file = PROMPTS_DIR / row["prompt_file"]

    prompt_files.append(prompt_file)

print("=" * 60)
print("Prompt Files Available")
print("=" * 60)

for file in prompt_files:
    print(file.name)

print()
print(f"Total Prompt Files : {len(prompt_files)}")

============================================================
Prompt Files Available
============================================================
problem_001_prompt.txt
problem_002_prompt.txt
problem_003_prompt.txt
problem_004_prompt.txt
problem_005_prompt.txt
problem_006_prompt.txt
problem_007_prompt.txt
problem_008_prompt.txt
problem_009_prompt.txt
problem_010_prompt.txt

Total Prompt Files : 10

# ============================================================
# Locate Prompt Files
# ============================================================

prompt_files = []

for _, row in manifest_df.iterrows():

    prompt_file = PROMPTS_DIR / row["prompt_file"]

    prompt_files.append(prompt_file)

print("=" * 60)
print("Prompt Files Available")
print("=" * 60)

for file in prompt_files:
    print(file.name)

print()
print(f"Total Prompt Files : {len(prompt_files)}")

In [25]:
# ============================================================
# Verify Prompt Files
# ============================================================

missing_files = []

for _, row in manifest_df.iterrows():

    prompt_path = PROMPTS_DIR / row["prompt_file"]

    if not prompt_path.exists():
        missing_files.append(prompt_path.name)

if len(missing_files) == 0:
    print("✓ All prompt files are available.")
else:
    print("Missing Prompt Files:")
    for file in missing_files:
        print(file)

✓ All prompt files are available.

In [26]:
# ============================================================
# Verify Prompt Files
# ============================================================

missing_files = []

for _, row in manifest_df.iterrows():

    prompt_path = PROMPTS_DIR / row["prompt_file"]

    if not prompt_path.exists():
        missing_files.append(prompt_path.name)

if len(missing_files) == 0:
    print("✓ All prompt files are available.")
else:
    print("Missing Prompt Files:")
    for file in missing_files:
        print(file)

✓ All prompt files are available.

## Manual AI Code Generation Procedure

Each prompt file was independently submitted to the selected Large Language Model (LLM).

For every benchmark problem:

- The same prompt was submitted three independent times.
- Each response was obtained in a fresh interaction to minimize conversational context effects.
- The returned Python programs were saved as:

- `solution_A.py`
- `solution_B.py`
- `solution_C.py`

The generated solutions were stored in the corresponding problem directory under `generated_code/`.

In [27]:
# ============================================================
# Create Problem Directories
# ============================================================

for pid in manifest_df["problem_id"]:

    problem_dir = GENERATED_CODE_DIR / f"problem_{int(pid):03d}"

    problem_dir.mkdir(parents=True, exist_ok=True)

print("✓ Problem directories created successfully.")

✓ Problem directories created successfully.

In [28]:
print("Generated Code Directories\n")

for folder in sorted(GENERATED_CODE_DIR.iterdir()):

    if folder.is_dir():
        print(folder.name)

Generated Code Directories

problem_001
problem_002
problem_003
problem_004
problem_005
problem_006
problem_007
problem_008
problem_009
problem_010

## Organization of Generated Solutions

Each benchmark problem has a dedicated directory with three independently generated Python solutions.

Example:

```
generated_code/
    problem_001/
        solution_A.py
        solution_B.py
        solution_C.py
```

This directory structure is used by Notebook 4 for automated functional evaluation.

## Verify Generated AI Solutions

This section verifies that the three generated Python solutions exist for every benchmark problem before functional evaluation.

In [29]:
# ============================================================
# Verify Generated Solutions
# ============================================================

verification_records = []

for _, row in manifest_df.iterrows():

    pid = int(row["problem_id"])

    problem_dir = GENERATED_CODE_DIR / f"problem_{pid:03d}"

    solution_A = problem_dir / "solution_A.py"
    solution_B = problem_dir / "solution_B.py"
    solution_C = problem_dir / "solution_C.py"

    verification_records.append({
        "problem_id": pid,
        "solution_A": solution_A.exists(),
        "solution_B": solution_B.exists(),
        "solution_C": solution_C.exists()
    })

verification_df = pd.DataFrame(verification_records)

display(verification_df)

   problem_id  solution_A  solution_B  solution_C
0           1        True        True        True
1           2        True        True        True
2           3        True        True        True
3           4        True        True        True
4           5        True        True        True
5           6        True        True        True
6           7        True        True        True
7           8        True        True        True
8           9        True        True        True
9          10        True        True        True

In [30]:
print("=" * 60)
print("Solution Verification Summary")
print("=" * 60)

print("Total Problems :", len(verification_df))

print()

print("Solutions Available")

print("Solution A :", verification_df["solution_A"].sum())
print("Solution B :", verification_df["solution_B"].sum())
print("Solution C :", verification_df["solution_C"].sum())

============================================================
Solution Verification Summary
============================================================
Total Problems : 10

Solutions Available
Solution A : 10
Solution B : 10
Solution C : 10

In [31]:
assert verification_df["solution_A"].all()
assert verification_df["solution_B"].all()
assert verification_df["solution_C"].all()

print("✓ All generated solutions verified successfully.")

✓ All generated solutions verified successfully.

In [32]:
manifest_df["status"] = "Completed"

display(manifest_df)

,problem_id,title,prompt_file,solution_A,solution_B,solution_C,status
0,1,Sum of Two Integers,problem_001_prompt.txt,NaN,NaN,NaN,Completed
1,2,Area of a Circle,problem_002_prompt.txt,NaN,NaN,NaN,Completed
2,3,Largest of Two Numbers,problem_003_prompt.txt,NaN,NaN,NaN,Completed
3,4,Print Numbers from 1 to N,problem_004_prompt.txt,NaN,NaN,NaN,Completed
4,5,Factorial of a Number,problem_005_prompt.txt,NaN,NaN,NaN,Completed
5,6,Prime Number Check,problem_006_prompt.txt,NaN,NaN,NaN,Completed
6,7,Largest Element in a List,problem_007_prompt.txt,NaN,NaN,NaN,Completed
7,8,Count Vowels in a String,problem_008_prompt.txt,NaN,NaN,NaN,Completed
8,9,Word Frequency Counter,problem_009_prompt.txt,NaN,NaN,NaN,Completed
9,10,Fibonacci Using Recursion,problem_010_prompt.txt,NaN,NaN,NaN,Completed

In [33]:
manifest_df.to_csv(manifest_path, index=False)

print("✓ Manifest updated successfully.")

✓ Manifest updated successfully.

## Reproducibility

The generated Python programs are organized in a standardized directory structure.

For every benchmark problem, three independent AI-generated solutions are stored as:

- `solution_A.py`
- `solution_B.py`
- `solution_C.py`

This standardized organization enables automated execution and functional evaluation in the next stage of the experimental pipeline.

## Conclusion

In this notebook:

- Prompt files were loaded successfully.
- Generated solution directories were verified.
- Three AI-generated Python solutions were organized for each benchmark problem.
- The experiment manifest was updated.
- All generated solutions were verified successfully.

The generated solutions are now ready for automated functional evaluation in Notebook 4.

In [34]:
print("=" * 70)
print("Notebook 3 Completed Successfully")
print("=" * 70)

print("Total Benchmark Problems :", len(manifest_df))
print("Prompt Files             :", len(prompt_files))
print("Generated Solutions      :", len(manifest_df) * 3)
print("Status                   : Ready for Notebook 4")

======================================================================
Notebook 3 Completed Successfully
======================================================================
Total Benchmark Problems : 10
Prompt Files             : 10
Generated Solutions      : 30
Status                   : Ready for Notebook 4